# SPDX-License-Identifier: GPL-2.0
subdir-y += google

dtb-$(CONFIG_ARCH_EXYNOS) += \
	exynos5433-tm2.dtb		\
	exynos5433-tm2e.dtb		\
	exynos7-espresso.dtb		\
	exynos7885-jackpotlte.dtb	\
	exynos850-e850-96.dtb		\
        exynos9820-beyond0lte.dtb	\
	exynos9820-beyond1lte.dtb	\
	exynosautov9-sadk.dtb		\
	exynosautov920-sadk.dtb
